// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package frame

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type f_chkpnt struct {
	_tab flatbuffers.Struct
}

func (rcv *f_chkpnt) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *f_chkpnt) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *f_chkpnt) PtrOfst() int16 {
	return rcv._tab.GetInt16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *f_chkpnt) MutatePtrOfst(n int16) bool {
	return rcv._tab.MutateInt16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func Createf_chkpnt(builder *flatbuffers.Builder, ptrOfst int16) flatbuffers.UOffsetT {
	builder.Prep(2, 2)
	builder.PrependInt16(ptrOfst)
	return builder.Offset()
}
