// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package frame

import "strconv"

type f_mode int8

const (
	f_modew f_mode = 0
	f_moder f_mode = 1
)

var EnumNamesf_mode = map[f_mode]string{
	f_modew: "w",
	f_moder: "r",
}

var EnumValuesf_mode = map[string]f_mode{
	"w": f_modew,
	"r": f_moder,
}

func (v f_mode) String() string {
	if s, ok := EnumNamesf_mode[v]; ok {
		return s
	}
	return "f_mode(" + strconv.FormatInt(int64(v), 10) + ")"
}
